apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.io'
      chart: podinfo
      targetRevision: 6.6.2
      helm:
        values: |
          replicaCount: 1
          ui:
            message: "test-here"

    - repoURL: 'git@github.com:dshershov/argocd-apps.git'
      targetRevision: main
      path: apps/lib/simple-app/templates   
  # source:
  #   repoURL: 'git@github.com:dshershov/argocd-apps.git'
  #   targetRevision: main
  #   path: apps/lib/test-app
  #   directory:
  #     recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
